package cz.maio

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class Day02Test {
    enum class RoundResult {
        Won,
        Draw,
        Lost;

        fun score(): Int {
            return when (this) {
                Won -> 6
                Draw -> 3
                Lost -> 0
            }
        }
    }

    enum class Choice {
        Rock,
        Paper,
        Scissors;

        fun score(): Int = when (this) {
            Rock -> 1
            Paper -> 2
            Scissors -> 3
        }

        fun compare(other: Choice): RoundResult {
            return when (this) {
                Rock -> when (other) {
                    Rock -> RoundResult.Draw
                    Paper -> RoundResult.Lost
                    Scissors -> RoundResult.Won
                }

                Paper -> when (other) {
                    Rock -> RoundResult.Won
                    Paper -> RoundResult.Draw
                    Scissors -> RoundResult.Lost
                }

                Scissors -> when (other) {
                    Rock -> RoundResult.Lost
                    Paper -> RoundResult.Won
                    Scissors -> RoundResult.Draw
                }
            }
        }

        companion object {
            fun of(s: String): Choice {
                return when (s) {
                    "A", "X" -> Rock
                    "B", "Y" -> Paper
                    "C", "Z" -> Scissors
                    else -> error("Unknown: $s")
                }
            }
        }
    }

    /**
     * A|X - Rock
     * B|Y - Paper
     * C|Z - Scissors
     *
     * Scoring:
     *
     * Shape Selected:
     * 1 for Rock
     * 2 for Paper
     * 3 for Scissors
     *
     * Outcome:
     * 0 if you lost
     * 3 if the round was a draw
     * and 6 if you won
     */

    private fun computePart1(input: String): Int {
        return input.lines().map {
            computePart1Single(it)
        }.sum()
    }

    private fun computePart1Single(line: String): Int {
        val (theirs, my) = line.split(" ").map { Choice.of(it) }

        return my.compare(theirs).score() + my.score()
    }

    @Test
    fun `sample input`() {
        val result = computePart1(
            """
            A Y
            B X
            C Z
        """.trimIndent()
        )

        assertThat(result).isEqualTo(8 + 1 + 6)
    }

    @Test
    fun `part 1 & 2`() {
        val result = computePart1(
            """
            B Z
            A X
            C X
            C X
            C Z
            C X
            C X
            A Z
            C X
            B Z
            B Z
            C X
            A X
            C X
            C X
            C X
            C Y
            C X
            C Z
            C X
            C X
            C X
            C X
            C X
            C Z
            C X
            C X
            A X
            C X
            B Y
            A X
            B X
            A Z
            C X
            B Y
            A X
            C Z
            C X
            C Z
            A X
            A Y
            B Z
            A Z
            C X
            A Z
            A Z
            A Y
            C Y
            A Y
            A Z
            C X
            A Y
            B Y
            A Z
            B Y
            C Z
            A X
            C X
            C Z
            B Z
            C X
            B Y
            C X
            A Z
            C X
            A X
            C X
            C X
            A Z
            B Z
            C X
            C X
            C Z
            C X
            B X
            C X
            A Z
            A X
            A Y
            A Y
            A Z
            C X
            C Z
            C X
            B Y
            C X
            C X
            A X
            A X
            C Z
            C X
            B X
            C Z
            C X
            C X
            C X
            B Z
            B Y
            A Z
            C X
            A Z
            C X
            C Z
            A Z
            C X
            A X
            C X
            C Z
            C Z
            C X
            C Z
            A Y
            C X
            A X
            A Z
            A X
            C Y
            B X
            C X
            A X
            A Y
            A X
            B Y
            A X
            C X
            B Y
            A Z
            C X
            B X
            C X
            A Y
            C Z
            C X
            C Z
            C X
            A Y
            A Z
            C X
            A Z
            B Y
            C X
            A Z
            C X
            C Z
            B Z
            C X
            C Z
            C X
            C Z
            C X
            A Y
            C X
            C X
            A Z
            C Z
            C X
            A X
            C X
            C X
            B Y
            C X
            C X
            C X
            C X
            C X
            A Y
            C Z
            C X
            C X
            C Z
            B X
            C X
            C X
            C Z
            B Y
            B Y
            C X
            C X
            A Z
            C Z
            C X
            C Z
            C X
            A Y
            A X
            A X
            A Y
            C X
            C X
            C X
            A Z
            B Z
            C Z
            A Y
            A Y
            C X
            C X
            B Y
            C X
            C X
            C X
            A Z
            B Y
            B Y
            C X
            C Y
            C X
            C Z
            B Y
            C X
            C X
            C Z
            A X
            B Y
            C X
            A Z
            C X
            A Z
            C X
            A Z
            C X
            C Z
            C X
            A Z
            C X
            A X
            C Z
            A Z
            A Y
            C X
            C Z
            B Y
            A Z
            C X
            B Y
            B X
            A Z
            C X
            C Y
            A X
            C Z
            A X
            C Z
            C Z
            C Z
            A Z
            C X
            C X
            A Z
            C X
            A X
            C X
            B X
            C X
            C X
            C Z
            C X
            C X
            C Z
            C X
            A Y
            C Z
            C Z
            A X
            A Z
            B X
            C X
            C X
            B X
            C Y
            C X
            A Y
            C Z
            A X
            C X
            A Y
            A Z
            C X
            A Y
            A Z
            A Z
            C Z
            C X
            A Y
            C X
            A X
            C X
            C X
            C X
            A Z
            C X
            C X
            A Z
            A X
            C X
            B Y
            B X
            C X
            C X
            A Y
            A Z
            B Z
            C Z
            A Z
            A X
            C Z
            A X
            C X
            B X
            C X
            B X
            C X
            A X
            C Z
            C X
            A Z
            A Y
            C X
            C Z
            C X
            A X
            C X
            B Y
            A Z
            C X
            C Z
            A X
            C X
            A Z
            C X
            B Y
            C X
            C Y
            C Y
            B Z
            C Z
            A X
            B Z
            C X
            C X
            A Z
            A X
            C X
            A X
            B Z
            A Z
            B Y
            B Y
            C X
            C X
            A Z
            A Z
            B Z
            A Z
            A Z
            A Z
            B Y
            C Z
            A Y
            A X
            C X
            C X
            C X
            C X
            C Z
            B Y
            C X
            A Z
            B Y
            B Y
            C X
            C X
            A X
            C X
            C Z
            C X
            A X
            A Z
            C Z
            C Z
            B Z
            B Y
            C Z
            C Z
            A X
            B Y
            C X
            C Z
            B Y
            C X
            C X
            C X
            C X
            B Z
            C X
            B X
            C Y
            C Z
            A Z
            C X
            C X
            C X
            A Z
            C X
            B Z
            C Z
            C Z
            C X
            C Z
            A Z
            C X
            C X
            C X
            C Z
            C Z
            C X
            C X
            C Z
            C X
            C Z
            C X
            A Z
            C X
            B Z
            B X
            B Z
            A Z
            A Z
            B Y
            C Y
            C X
            C X
            C X
            C X
            A X
            C X
            A X
            C X
            C X
            A Z
            C X
            C X
            B Y
            C Z
            C X
            C X
            A Y
            A X
            C Z
            C Z
            C X
            C X
            C X
            B X
            C Z
            C X
            C X
            C X
            B X
            A Y
            B Z
            C X
            B Y
            C X
            C X
            C X
            B X
            B Y
            A Z
            A Z
            A Z
            C X
            A Z
            C Z
            B Z
            C X
            A Z
            C X
            C X
            C X
            A Y
            B Y
            C X
            B Y
            C Z
            C X
            B X
            A Z
            C X
            A X
            C X
            C Z
            C Z
            B Y
            C Z
            C X
            C X
            B X
            C X
            C X
            C X
            C X
            A Z
            B Y
            A X
            C X
            A Y
            B X
            A Z
            A Z
            C X
            A Y
            C Z
            A Z
            A X
            A Y
            C X
            C Z
            C Z
            C Z
            C X
            B Y
            C X
            A Y
            C X
            A Z
            C X
            C Z
            C X
            B X
            C Z
            C Y
            C X
            B Z
            A X
            B X
            C X
            B Y
            C Z
            C Z
            C Z
            C X
            A Z
            C Z
            C X
            C X
            C X
            B Z
            C X
            C X
            A Z
            C X
            A Z
            C Z
            A Z
            A Z
            A Z
            C X
            A X
            C X
            A Z
            A Y
            C X
            A Z
            C X
            B Y
            A X
            C Z
            A Z
            C Z
            A Y
            C X
            A Z
            C Z
            C X
            C X
            C X
            C Y
            C X
            A Y
            A Z
            A X
            C Z
            C Z
            A Y
            C X
            C X
            B Y
            B Z
            C X
            B Y
            C Z
            C Z
            C X
            C Z
            B Y
            C Z
            B Y
            C Z
            B Y
            C X
            A X
            A X
            C X
            A Z
            A Z
            C X
            C X
            B Y
            A Z
            C Z
            A X
            C Z
            C X
            C Y
            A Z
            A Z
            C X
            C X
            A X
            C X
            C Z
            C X
            B Z
            C X
            A Z
            A Z
            C X
            A Z
            A X
            A Z
            C Y
            B Y
            C X
            C X
            C Z
            C Z
            C Z
            C Z
            C X
            A X
            C X
            B Y
            C X
            B Y
            B Y
            B X
            C X
            C X
            C X
            C X
            C X
            C Z
            A X
            C X
            C X
            A Z
            A Z
            C X
            A Z
            C X
            C Z
            C X
            B Z
            A Z
            C X
            C X
            C X
            C Z
            A Z
            B Y
            C X
            C X
            C Z
            C X
            C X
            C X
            A Z
            B Z
            A X
            C Z
            C X
            C X
            A X
            C X
            C X
            C X
            A Z
            A Y
            C Y
            C Z
            C X
            C Z
            C Z
            A Z
            C X
            C X
            B X
            C Z
            A Y
            C X
            C X
            C X
            C Z
            C X
            C Z
            C X
            C X
            C X
            B X
            C X
            A Z
            B X
            B Y
            C X
            A Z
            A Z
            C X
            A Y
            C X
            C Z
            A Z
            B Z
            A Z
            B Y
            A X
            A Y
            B X
            C X
            B Z
            C Z
            B Y
            C X
            A Z
            C Z
            C Z
            C Z
            B X
            C X
            A X
            B Y
            C X
            C X
            A X
            B Z
            B X
            C X
            C X
            A X
            C X
            C X
            C X
            C X
            C Z
            C X
            A Z
            B Y
            A Y
            B Y
            A X
            C X
            A Y
            A Z
            C X
            C X
            B Y
            C X
            B Y
            C Z
            C X
            C X
            B Y
            C X
            A Z
            C Z
            C X
            C X
            C Z
            C X
            C X
            B Y
            B Y
            C X
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            B Z
            B Y
            A Z
            C X
            C X
            C X
            A Y
            C X
            A Y
            A X
            A Z
            B X
            C X
            A X
            B X
            A Z
            C Z
            C X
            A Z
            A X
            C X
            C X
            C X
            C X
            B Z
            A X
            A X
            C Z
            C X
            C X
            A Y
            C Z
            C X
            B Y
            C X
            B Y
            C X
            C X
            B X
            C X
            A Z
            C Z
            C X
            C X
            C X
            C X
            A Z
            A Y
            C Z
            C X
            B X
            A Y
            A X
            A X
            B X
            C X
            C X
            A X
            C X
            C Z
            A X
            C Z
            C X
            B Y
            C X
            C X
            C Z
            C X
            B Z
            C X
            C X
            C Z
            B Z
            C X
            C Z
            A Z
            C X
            B X
            C X
            C X
            C X
            C X
            C X
            C X
            A Z
            A Z
            B Z
            A Y
            A Z
            B X
            A Y
            B Y
            C X
            C X
            C Z
            C X
            C X
            C X
            A Y
            C X
            C X
            B X
            C Z
            C X
            C X
            C X
            C X
            B Y
            A Y
            C X
            A Z
            C X
            C X
            C Z
            C X
            C Z
            C X
            C X
            B Y
            A Z
            B X
            A X
            C X
            C Z
            C X
            C X
            C X
            C X
            C X
            B Z
            C X
            C X
            C Z
            B Y
            C X
            B Y
            C X
            C X
            C X
            C X
            C Z
            C X
            A Y
            C X
            C Z
            A Y
            A X
            B Z
            C Z
            C X
            A X
            C X
            A Y
            C X
            C X
            B X
            C X
            B X
            B Z
            A Z
            A X
            C X
            A Z
            C X
            C X
            C X
            C X
            A Y
            C Y
            A X
            C Z
            A Y
            C X
            A Z
            C X
            C X
            C X
            A Y
            C X
            C X
            C X
            C X
            A X
            C X
            A Z
            A Z
            A X
            A Z
            C Z
            C X
            B Y
            A Y
            C X
            C X
            C X
            C X
            A Z
            C X
            A Z
            B X
            B Y
            C X
            A Z
            A X
            C X
            C Z
            C X
            C X
            C Z
            C X
            C Z
            B X
            C X
            C X
            C X
            A X
            A Z
            C Z
            C Y
            C X
            A Y
            B Y
            C X
            B Y
            C X
            C X
            C X
            A Z
            C X
            B Z
            A Y
            C X
            C X
            B Y
            A X
            C Z
            C X
            B Y
            C Z
            A Y
            B Y
            B Z
            C X
            C X
            A Z
            C X
            C Z
            C Y
            A X
            B Y
            C Y
            A X
            C Z
            C Y
            C X
            A Y
            B Z
            C X
            A Z
            C X
            B Y
            C X
            C Y
            C X
            C Z
            C X
            A Z
            C Z
            C X
            C X
            C X
            B X
            A Z
            C X
            C X
            C Z
            C Y
            C Z
            C X
            C X
            C Z
            A X
            C Z
            C Y
            B Y
            C X
            B Y
            C Z
            C X
            C X
            C X
            A X
            B X
            C X
            B Z
            A Y
            C X
            C Z
            B Y
            C X
            C X
            C X
            C Z
            C X
            C X
            C X
            C X
            A Y
            C X
            B X
            C Y
            A X
            B Y
            A Z
            C X
            C X
            A Z
            C Z
            C X
            C Z
            A Y
            A X
            C Z
            A Z
            C Y
            A Z
            B Y
            C X
            A Z
            C X
            C Z
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C Z
            B X
            A Y
            C X
            C X
            C Z
            A Y
            A Z
            A Z
            B Y
            C X
            C Z
            C X
            C Z
            C X
            C X
            C X
            C X
            A Z
            A X
            A Z
            C X
            A Y
            B Y
            C X
            C Y
            A Z
            B X
            C Z
            A X
            C X
            C X
            C X
            C X
            C X
            A Y
            A Z
            C X
            C X
            A X
            C Z
            A Z
            A X
            C X
            B Y
            A X
            C Z
            B Y
            C X
            A Z
            B Z
            C X
            C Z
            C Z
            B X
            B Y
            C Z
            A X
            C Z
            C Z
            A Y
            A Y
            C X
            C X
            C X
            C X
            A Y
            C X
            A Z
            C X
            C X
            C X
            C X
            C X
            B Y
            C Z
            C X
            C X
            C Z
            C X
            C X
            B Z
            C X
            A Z
            A Z
            C X
            A X
            C X
            C X
            B Z
            C X
            A Z
            C X
            B X
            C X
            C Z
            C X
            A X
            C X
            B Y
            A X
            C Z
            C Z
            C X
            C X
            C Z
            C X
            C X
            C X
            A Z
            A X
            C X
            B X
            C Z
            A Z
            C Z
            B Z
            C X
            A X
            C X
            C X
            C Z
            C X
            A Y
            A Y
            C Z
            C X
            B Y
            B Z
            C X
            B X
            C X
            C X
            A Z
            C Z
            C Z
            C X
            B X
            A Z
            C X
            C Z
            A X
            C Z
            C Z
            A Z
            A Y
            A Z
            C X
            C X
            C X
            A Z
            A Y
            C X
            A Z
            B Z
            C X
            B X
            B X
            C Z
            C Z
            C Z
            C X
            C X
            C X
            A Z
            C X
            C X
            C X
            C X
            A Z
            C X
            C Y
            A X
            C X
            C X
            B Y
            C X
            C X
            A X
            C Z
            C Z
            C Z
            A Z
            C X
            C X
            C X
            A Y
            C Z
            C X
            C X
            C X
            C Y
            C Z
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            A X
            C X
            A X
            C X
            C X
            A Z
            C X
            C X
            A Y
            C Z
            A X
            A Y
            C X
            A Z
            B Y
            B Y
            A X
            C Z
            C X
            C X
            C X
            A X
            A Z
            B Y
            C X
            A Y
            C X
            C X
            B Y
            C X
            C X
            C X
            B Y
            C X
            C Z
            C X
            C Z
            A Y
            B Y
            C X
            C Z
            C X
            B X
            A Z
            C Z
            C Z
            C Z
            C X
            B Z
            C X
            B X
            C Y
            C Z
            C X
            C X
            C Z
            A Z
            B X
            C X
            C X
            A Z
            C X
            A Z
            C X
            A Y
            C X
            C Z
            A Z
            A X
            C X
            B X
            C X
            C X
            C X
            C Y
            B X
            C X
            B Y
            C X
            C Y
            A Z
            A Y
            C X
            A Z
            C Z
            A Y
            B Y
            C Z
            A X
            A X
            B X
            C X
            C X
            C Z
            A X
            B Y
            A X
            C Z
            C X
            C X
            C X
            A X
            C X
            C X
            C X
            C Y
            C X
            C X
            C Z
            C X
            C X
            C X
            A Z
            B X
            A Z
            C X
            A X
            C X
            B Y
            B Z
            C X
            C X
            A Z
            C X
            A Y
            B X
            C X
            C X
            C Z
            B Y
            C X
            A Y
            C X
            B Z
            C X
            A Z
            C Z
            C X
            C X
            C X
            C Z
            A X
            B X
            C Z
            B Y
            C Z
            C X
            B Y
            A Z
            C X
            C X
            C X
            C X
            C Z
            A X
            A Y
            A Z
            C X
            C X
            B Y
            B Y
            C X
            A X
            B Y
            A Y
            C X
            C X
            C X
            A X
            B X
            B Y
            A Z
            C X
            C X
            C Z
            A X
            C X
            A X
            A Z
            C X
            A Z
            C X
            C Z
            C Z
            B Z
            C X
            B Y
            C Z
            C X
            A Z
            C X
            C X
            C X
            C X
            C X
            C Y
            C X
            C X
            A Z
            C X
            A X
            A Y
            B Y
            C X
            A Y
            B X
            C Z
            C X
            A Z
            C X
            C X
            C X
            A Z
            B Z
            C Z
            B Z
            C X
            C X
            C Y
            C Z
            C X
            C Z
            C X
            C X
            C X
            B X
            C X
            C X
            A Z
            B Y
            C Z
            C Z
            C X
            A Z
            B Y
            A X
            C X
            A Z
            C Z
            C X
            C X
            A Z
            A X
            C Y
            B Z
            A X
            C X
            A Z
            C X
            C Z
            A Z
            C X
            A Y
            C X
            C X
            B Z
            C X
            C Z
            A Z
            A Z
            C X
            B Z
            B X
            A Z
            A X
            C X
            C X
            C X
            C Z
            C X
            A X
            C X
            C X
            B X
            C Z
            C X
            C X
            C Y
            A Z
            B Y
            A Z
            B Y
            C X
            A Z
            C Z
            C Y
            B Z
            A X
            C X
            C X
            A Y
            B Y
            A X
            C Z
            A Z
            C X
            C X
            B Y
            B Y
            C X
            C X
            C X
            C X
            C X
            C Z
            A X
            A X
            A X
            C Z
            C X
            A X
            C Z
            B Z
            C Z
            C X
            A X
            A Y
            C X
            A Z
            C X
            C X
            C Z
            C Z
            C X
            A X
            A X
            C Y
            A Y
            C X
            C Z
            A X
            A Y
            A Z
            B Y
            C X
            B Y
            A Z
            B X
            C X
            C Z
            C X
            B Z
            A Z
            A Z
            C Z
            C X
            C X
            C Y
            C X
            B X
            C X
            C Z
            A X
            C Y
            A Z
            C X
            C X
            A Z
            A Z
            A Z
            C Z
            A Z
            C X
            B X
            B Y
            C X
            A Z
            C Z
            C X
            C X
            C X
            A X
            B Y
            A Z
            B Y
            C X
            B Z
            A Z
            C Z
            C Z
            C X
            C X
            C X
            A Z
            C X
            A X
            C Z
            A Y
            C X
            A Y
            C X
            C Z
            C X
            C X
            C X
            B Y
            C X
            B Y
            C Z
            B Y
            B Z
            A Z
            A X
            C Z
            C X
            C X
            B Y
            B Y
            A Z
            C X
            C Z
            C Z
            C Z
            B Z
            B Y
            B X
            C X
            C X
            C X
            C Z
            C X
            C X
            B Y
            C X
            C X
            B Y
            C X
            C X
            C X
            C X
            A Y
            C X
            C X
            A Z
            C Z
            A Z
            A Z
            A Y
            A Z
            C Z
            C X
            C X
            C X
            C X
            B Y
            A Z
            C X
            C X
            B Y
            A Y
            A Z
            A Z
            C Z
            C X
            C Y
            C X
            C X
            B Y
            C X
            A X
            B X
            B Y
            C Z
            A X
            C X
            C X
            A X
            C X
            A Y
            A Y
            C X
            C X
            B Y
            C X
            A Z
            C Z
            A X
            C X
            A Z
            C X
            C X
            C X
            C Z
            A Z
            B X
            C X
            A Z
            C Z
            B Y
            C X
            C X
            B X
            C X
            C X
            A Y
            B Z
            B Y
            C X
            C X
            C X
            C Z
            C X
            C X
            C X
            B Y
            C X
            C Z
            C X
            A Z
            B Y
            A X
            B Y
            A Z
            C X
            C X
            A Z
            B Y
            C X
            A Z
            C X
            A Z
            A Z
            B Z
            A Y
            A Z
            C X
            C Z
            C X
            A X
            C X
            B Y
            B X
            C Z
            C X
            B Y
            C Z
            C X
            B Y
            C X
            C Y
            C Z
            A X
            B Z
            C X
            C X
            C Z
            A Z
            C X
            C Z
            A Z
            C X
            C X
            C Z
            C Z
            B Y
            A Z
            C X
            B X
            B Y
            C X
            C X
            C X
            C X
            B Z
            A Z
            C X
            A Z
            A X
            A Z
            C X
            A X
            C Z
            A Z
            C Z
            B Z
            B Y
            C X
            A X
            C Z
            C Z
            A Y
            B X
            C X
            C X
            A X
            C X
            C X
            C X
            A Z
            A Z
            C X
            A Z
            C Z
            C Z
            C X
            C Z
            B Y
            C X
            C X
            C X
            A Z
            A Z
            C X
            C X
            C X
            C Z
            A Z
            C X
            A X
            C Z
            C X
            B Y
            C X
            C Z
            C X
            C X
            A X
            A X
            B Y
            C Z
            C X
            C Z
            A Z
            C X
            A X
            A Z
            C X
            C X
            C Y
            C X
            A Z
            C X
            A Z
            B X
            A X
            A Z
            A Z
            A Z
            A Y
            A X
            C X
            C X
            A Z
            C Z
            C X
            C X
            A Z
            C Z
            C X
            C X
            C X
            C X
            C X
            C X
            A Z
            A Y
            C Z
            C X
            A Z
            A X
            C X
            C Z
            A Z
            C X
            B Y
            A Z
            A Z
            C X
            A Z
            C X
            C X
            A Z
            C X
            C Y
            C X
            C X
            B Y
            A Y
            A Z
            C X
            C X
            B Y
            C X
            C X
            C Z
            C Z
            C X
            B X
            C X
            C Z
            A Y
            C Z
            B Y
            C X
            C X
            B Y
            A Z
            B Y
            C Z
            A Y
            A Z
            B Y
            A X
            C X
            C X
            C Z
            C X
            A X
            C X
            C X
            C Z
            A Z
            A Z
            A Z
            C Z
            B X
            A Z
            A Z
            C X
            C X
            C X
            A Y
            A Z
            C Z
            C X
            C Z
            C X
            A Z
            C Z
            A Z
            C X
            B Y
            C Z
            C X
            C X
            A Z
            C Z
            C Z
            B X
            C Z
            C Z
            A Z
            A Y
            C X
            C X
            C Z
            C X
            A X
            C X
            C X
            C X
            C Z
            B Y
            B Y
            C X
            B Y
            C X
            C X
            C X
            A Z
            B Z
            C X
            C X
            C X
            C X
            C Z
            C X
            C X
            C X
            A Z
            C X
            B Y
            C X
            A Y
            B Z
            A Z
            C X
            B X
            A Y
            C Z
            C X
            C X
            C X
            C Z
            A Y
            C Y
            C X
            A Y
            A Y
            C X
            C X
            C X
            C X
            C Z
            B X
            C X
            C X
            C X
            A Z
            B X
            C X
            C X
            B Y
            C X
            C X
            C X
            A Z
            C X
            C X
            C X
            B Y
            C X
            B Z
            B X
            C Z
            C X
            C Z
            C X
            B X
            A Z
            C X
            C X
            A Z
            C Z
            C X
            A Z
            B Z
            C X
            A X
            A Z
            C Z
            C X
            C X
            B X
            B X
            C X
            B X
            C X
            C Z
            C X
            C X
            A Y
            A X
            A X
            C Z
            C Z
            A Z
            C Z
            C X
            C X
            C X
            C Z
            A X
            C Z
            A X
            C Z
            C X
            C X
            A Y
            C Z
            A Z
            A X
            A Z
            B Y
            C X
            C Z
            C X
            C X
            A X
            A X
            C X
            C X
            C X
            C X
            A Z
            C X
            C Z
            A X
            C X
            B Y
            C Z
            C X
            A X
            C X
            C Z
            C X
            A X
            A X
            A X
            C X
            A Z
            A X
            C Z
            C Z
            C X
            C Y
            A Y
            C X
            C X
            B X
            C X
            C X
            C Z
            B Y
            A Z
            C X
            B Y
            A Z
            C Z
            A Z
            A Y
            C Z
            B Z
            A X
            B Z
            C Z
            A X
            C Z
            A Z
            A Z
            B Z
            C X
            C X
            C X
            C X
            A X
            C X
            C X
            C X
            C X
            C X
            B Y
            C X
            C X
            C X
            B Z
            A Y
            A X
            C Z
            C X
            A Y
            B Y
            C X
            A Y
            A Z
            B X
            A Z
            C X
            B Y
            C X
            A Z
            A Z
            C X
            A Z
            A Z
            C X
            A X
            A Z
            C Z
            B Z
            C X
            A X
            C Y
            A Y
            C X
            A Z
            C X
            C X
            C X
            C Z
            C X
            C X
            C X
            A Y
            B Z
            A X
            A Z
            A Z
            C X
            A X
            B X
            C X
            B X
            C X
            A Z
            A X
            C X
            A X
            A Y
            A Y
            A Z
            A Z
            C X
            B X
            C X
            A Y
            C Z
            A Z
            C X
            C X
            A Y
            A Z
            B Y
            C X
            C X
            C X
            C X
            C X
            A Z
            C Z
            C X
            C X
            C Z
            C X
            C Z
            B Y
            C X
            A Z
            B X
            C Z
            C X
            C Z
            C Z
            C Z
            C X
            C X
            C Z
            C X
            C Z
            B Y
            C X
            C X
            A Z
            C X
            C X
            B Y
            C X
            C Z
            C X
            B X
            C Z
            A X
            C X
            C Z
            C X
            C Z
            B Y
            C X
            A Z
            A Y
            C X
            C Y
            B Z
            B X
            C X
            C X
            C Z
            C X
            B Y
            C X
            A Z
            A Y
            C X
            B Y
            C X
            C Z
            B Y
            C X
            A Y
            C X
            C X
            C X
            A Z
            C Z
            C X
            C X
            A X
            A Z
            C X
            C X
            A Y
            C X
            B Y
            C Z
            C Z
            C Z
            B Y
            C X
            C X
            C X
            C X
            A Y
            A Z
            A X
            C Z
            A Z
            A Z
            A Z
            C X
            A Y
            B X
            A Z
            C X
            C X
            B X
            C X
            C X
            C X
            B Y
            A Z
            A X
            A Z
            C X
            B X
            A X
            C X
            C X
            C X
            C X
            C X
            C Z
            A Z
            C X
            C X
            C Z
            C X
            A Y
            A Z
            C X
            A Z
            C X
            A Z
            C Z
            A Z
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            C X
            B Z
            C X
            A X
            C Z
            C X
            A X
            C Z
            A X
            B Y
            A Y
            C X
            A Z
            C X
            C X
            C X
            C X
            C X
        """.trimIndent()
        )

        assertThat(result).isEqualTo(14297)
    }
}
